GET http://localhost:4341/blocks

###

###
GET http://localhost:4341/blocks/test1


###
POST http://localhost:4341/blocks
Content-Type: application/json

{
    "index":2,
    "nonce": 5147,
    "data": { "text" : "ben is the king"},
    "type_code": "test1"
}

###
POST http://localhost:4341/chain
Content-Type: application/json

{"index":2}